### ISSUE TITLE
Plans for TinyMCE 5?

### ISSUE THREAD

**Issue by merwok** [dani0805/django-tinymce4#10]
Hello!  Are there plans to make a version that uses TinyMCE 5?

**Comment by vanadium23** [comment]
@merwok this project is deprecated. Either open issue on [aljosa/django-tinymce](https://github.com/aljosa/django-tinymce/issues) or you can use alternative - https://github.com/vanadium23/django-tinymce-lite and change TINYMCE_JS setting.
