### ISSUE TITLE
Where to submit pull requests for django-tinymce4?

### ISSUE THREAD

**Issue by romanvm** [dani0805/django-tinymce4#2]
I have some enhancements for this app, e.g. I've got integration with `django-filebrowser` working the same way it does in tinymce3. Where should I submit a pull request, here or to [aljosa/django-tinymce](https://github.com/aljosa/django-tinymce)?

**Comment by dani0805** [comment]
The tinymce 3 and 4 branches where so far apart that we decided to make a new package, if you do a pull request here I might be able to release it sometime next week, but my time lately has been somewhat scarce, if anyone wants to jump in and help out I would be happy.

---

INTRANETSTANDARD GmbH

Daniele Bernardini
Ottostr. 3, 
80333 Munich, Germany

mobile:     +49 151 22653325
email:  daniele.bernardini@intranetstandard.com
web:            www.intranetstandard.com

Geschäftsführer/Director  Daniele Bernardini
Amtsgericht                 München HRB 160411
UST-Id                  DE246453868

---

**Comment by romanvm** [comment]
Thanks. I don't expect it to be completed within the next week, because I need to try some ideas and polish my code. So I submit it as soon as it's ready.

BTW, in my setup I have a cosmetic issue: the top menu bar is shifted to the right as if left padding has been added to it. Lower toolbars are OK. I've inspected the html/css code in Firefox developer console but couldn't find the culprit. Do you have any ideas?
